version: '3.2'
services:
  test-mikro-db:
    image: mysql:5.7
    networks:
      - test-mikro
    ports:
      - 3316:3306
    environment:
      MYSQL_DATABASE: test_mikro
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test

networks:
  test-mikro:
